name: Run Notebook Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Jupyter Notebook and nbval plugin
        run: |
          pip install notebook nbval

      - name: Run Notebook Test
        run: |
          jupyter nbconvert --execute --to notebook --inplace test_monte_carlo_simulation.ipynb
