name: Test predprey Client

on: [push, pull_request]

jobs:
  execute-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install papermill jupyter numpy matplotlib scipy pytest umbridge arviz

    - name: Run UM-Bridge Servers as Notebooks
      run: |

        # Set enviromental variables
        export MODEL_URL="http://0.0.0.0:4242"
        export INPUT_VALUE="0.1"
        
        # Convert notebook to script
        cd Models/Predator-Prey
        jupyter nbconvert --to script predprey_server.ipynb
        notebook_script="${notebook%.ipynb}.py"
            
        # Run the notebook script in the background
        python predprey_server.py > /dev/null &
        notebook_pid=$!
        echo "Notebook script PID: $notebook_pid"
            
        echo "Waiting for model server to respond at $host:$port..."
        while ! curl -s "http://0.0.0.0:4242/Info" > /dev/null; do
          sleep 1
        done
        echo "Model server responded"

        # Run first client
        jupyter nbconvert --execute --to notebook --inplace predprey_client.ipynb
        script_exit_code=$?
        echo "Script exit code: $script_exit_code"

        # Run second client
        jupyter nbconvert --execute --to notebook --inplace predprey_firstclient.ipynb
        script_exit_code2 = $?
        echo "Script exit code: $script_exit_code2"

        # Add exit codes
        script_exit_code=$((script_exit_code + script_exit_code2))

        echo ""

        if [ $script_exit_code -eq 0 ]; then
          echo "pred prey clinets completed successfully."
        else
          echo "Error: pred prey clients failed with exit code $script_exit_code."
        fi

        # Terminate the notebook process
        if kill -0 $notebook_pid 2>/dev/null; then
          echo "Terminating notebook process with PID $notebook_pid"
          kill $notebook_pid
          wait $notebook_pid
          echo "Notebook process terminated."
        else
          echo "Notebook process already terminated."
        fi
